version: '3.4'

services:
  whisper:
    image: haoxian/whisper-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    cpu_count: 2
    mem_limit: 4g
    healthcheck:
      test: ["CMD", "curl",  "-f",   "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8000:8000
